name: Long Usage

on: push

permissions:
  pages: write
  id-token: write

env:
  REPO_URL: ${{ github.server_url }}/${{ github.repository }}
  PAGES_URL: ${{ steps.deployment.outputs.page_url }}

jobs:
  convert:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make dist Directory
        run: mkdir -p dist

      - name: Make link QR Code
        uses: snow-actions/qrcode@v1.0.0
        with:
          text: ${{ env.PAGES_URL }}
          path: 'static/qrcode.png'
        

      - name: Copy static files
        run: cp -r static dist/static

      - name: Build our Talk
        uses: docker://pandoc/core:2.9
        with:
          args: >-
            --slide-level 2
            -t dzslides
            -s talk.md
            -o dist/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Print envs
        run: echo "Deployed To ${{ steps.deployment.outputs.page_url }}"
